version: '3.8'
networks:
  app-network:
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: 'nginx_homecare'
    ports:
      - '8000:80'
    volumes:
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - app-network
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql_homecare'
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: homecare
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SEVICE_NAME: mysql
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'php_homecare'
    volumes:
      - './src:/var/www/html'
    ports:
      - '9000:9000'
    networks:
      - app-network
      

  npm:
    image: 'node:19.0.1-alpine3.15'
    container_name: 'npm_homecare'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    networks:
      - app-network
    entrypoint:
      - npm

  composer:
    image: 'composer:2.4.4'
    container_name: 'composer_homecare'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    networks:
      - app-network